version: '2'

services:

  castle-black:
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "8080:3000"
    volumes:
      - .:/var/www/
    networks:
      - westeros

  citadel-library:
    image: postgres
    networks:
      - westeros

networks:
  westeros:
      driver: bridge

