version: '3'

services:

  castle-black:

    build:
      context: .
      dockerfile: .castle-black.dockerfile
      args:
        environment: production

    container_name: wall

    ports:
      - "8080:8080"

    volumes:
      - ./:/home/node/
      - /home/node/node_modules/

    networks:
      - westeros

  citadel-library:

    image: postgres

    networks:
      - westeros

networks:

  westeros:

      driver: bridge
